### ISSUE TITLE
Report `devtest` numbers

### ISSUE THREAD

**Issue by satwikkottur** [seo-95/dstc9-SIMMC#4]
Hello @seo-95 ,

Could you please add the `devtest` numbers for your model to help us cross-check evaluation at our end?

Thanks!

**Comment by seo-95** [comment]
Hi @satwikkottur,
I have just added the file `mm_response_generation/model_outputs/dstc9-simmc-devtest-fashion-subtask-2-retrieval-scores.txt` that contains the precomputed scores for the `devtest` data split on the `dstc9-submission` branch. To reproduce the results on your end I also included the `mm_response_generation/model_outputs/dstc9-simmc-devtest-fashion-subtask-2-retrieval.json` file containing the model predictions on `devtest`.
commit: 50561ae158d3beae38fb43fc81fbe8d4114596bf

**Comment by satwikkottur** [comment]
Thanks @seo-95 !

If possible, could you also add numbers on `devtest` for all the other subtasks you're participating? Make sure you evaluate on every round of the dialog. We will also compute these at our end but this would serve as an additional layer of confirmation. Thank you!

**Comment by seo-95** [comment]
@satwikkottur we finally decide to participate to the retrieval task only for subtask#2. You can find everything about evaluation in the `mm_response_generation/model_outputs/` folder. Thank you!

**Comment by satwikkottur** [comment]
Hello @seo-95 ,

I could not find `model_outputs/` folder in `mm_response_generation/`. Am I missing something? Could you please link the folder?

Just to confirm, your participation in only for subtask#2 and in particular, only the retrieval category. Is this accurate?

Thanks!

**Comment by seo-95** [comment]
@satwikkottur the folder is on the branch called `dstc9-submission`. This is the link to the folder [model_outputs](https://github.com/seo-95/dstc9-SIMMC/tree/dstc9-submission/mm_response_generation/model_outputs).

I confirm our participation in subtask #2 and in particular to the retrieval category only.

**Comment by satwikkottur** [comment]
Thanks @seo-95 !
